// <auto-generated />
using System;
using Elevator.Management.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Elevator.Management.Persistence.Migrations
{
    [DbContext(typeof(ElevatorDbContext))]
    [Migration("20220302224658_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Elevator.Management.Domain.Entities.Building", b =>
                {
                    b.Property<Guid>("BuildingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("FirstFloor")
                        .HasColumnType("int");

                    b.Property<int>("LastFloor")
                        .HasColumnType("int");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BuildingId");

                    b.ToTable("Buildings");

                    b.HasData(
                        new
                        {
                            BuildingId = new Guid("b0788d2f-8003-43c1-92a4-edc76a7c5dde"),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstFloor = -2,
                            LastFloor = 14,
                            Name = "Masiv"
                        });
                });

            modelBuilder.Entity("Elevator.Management.Domain.Entities.Elevator", b =>
                {
                    b.Property<Guid>("ElevatorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BuildingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CurrentFloor")
                        .HasColumnType("int");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.HasKey("ElevatorId");

                    b.ToTable("Elevators");

                    b.HasData(
                        new
                        {
                            ElevatorId = new Guid("6313179f-7837-473a-a4d5-a5571b43e6a6"),
                            BuildingId = new Guid("b0788d2f-8003-43c1-92a4-edc76a7c5dde"),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentFloor = -1,
                            Name = "A",
                            State = 1
                        },
                        new
                        {
                            ElevatorId = new Guid("bf3f3002-7e53-441e-8b76-f6280be284aa"),
                            BuildingId = new Guid("b0788d2f-8003-43c1-92a4-edc76a7c5dde"),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentFloor = 11,
                            Name = "B",
                            State = 2
                        },
                        new
                        {
                            ElevatorId = new Guid("fe98f549-e790-4e9f-aa16-18c2292a2ee9"),
                            BuildingId = new Guid("b0788d2f-8003-43c1-92a4-edc76a7c5dde"),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentFloor = 4,
                            Name = "C",
                            State = 0
                        });
                });

            modelBuilder.Entity("Elevator.Management.Domain.Entities.Movement", b =>
                {
                    b.Property<Guid>("MovementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DestinationFloor")
                        .HasColumnType("int");

                    b.Property<Guid>("ElevatorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("MovementId");

                    b.HasIndex("ElevatorId");

                    b.ToTable("Movements");

                    b.HasData(
                        new
                        {
                            MovementId = new Guid("830be110-0361-4cf9-8004-2a1693aad8f7"),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DestinationFloor = 3,
                            ElevatorId = new Guid("6313179f-7837-473a-a4d5-a5571b43e6a6")
                        },
                        new
                        {
                            MovementId = new Guid("2d7f6e52-007e-4c23-a863-85e16d829d1a"),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DestinationFloor = 2,
                            ElevatorId = new Guid("6313179f-7837-473a-a4d5-a5571b43e6a6")
                        },
                        new
                        {
                            MovementId = new Guid("64c54d08-1349-4430-b39c-9537a044dbf5"),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DestinationFloor = 4,
                            ElevatorId = new Guid("6313179f-7837-473a-a4d5-a5571b43e6a6")
                        },
                        new
                        {
                            MovementId = new Guid("16a80793-4576-4534-be86-fb6fafa9f0fe"),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DestinationFloor = 5,
                            ElevatorId = new Guid("bf3f3002-7e53-441e-8b76-f6280be284aa")
                        },
                        new
                        {
                            MovementId = new Guid("23ec86e9-510d-4e76-8c5d-b769c36ed01f"),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DestinationFloor = 8,
                            ElevatorId = new Guid("bf3f3002-7e53-441e-8b76-f6280be284aa")
                        });
                });

            modelBuilder.Entity("Elevator.Management.Domain.Entities.Movement", b =>
                {
                    b.HasOne("Elevator.Management.Domain.Entities.Elevator", "Elevator")
                        .WithMany("Movements")
                        .HasForeignKey("ElevatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
